apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PodSecurityPolicy
metadata:
  name: pod-always-nonadmin
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    message: "Admin Pods are restricted to Create"